### ISSUE TITLE
How can I move the postcss configuration to a seperate file and use svelte-preprocess without breaking tailwind?

### ISSUE THREAD

**Issue by GitGangGuy** [EricPKerr/sapper-tailwindcss#5]
As to be seen in my [fork](https://github.com/GitGangGuy/sapper-tailwindcss-issue), a very simple modification I did in a personal project of mine broke the whole tailwind injection. Why? Any help is very much appreciated!

**Comment by RStrydom** [comment]
Hey @GitGangGuy ,
I was also looking at this template and also wanted the separate postcss config and svelte-preprocess setup.

Luckily before I got here I used another guide successfully - https://dev.to/sarioglu/using-svelte-with-tailwindcss-a-better-approach-47ph

I have combined the two and have it working as expected.
I am not a fan of fragmenting things further so I have attached the files here. Although if @EricPKerr is interested we could create a PR to pull it into the main Repo.

Let me know if this works for you :smile: 
[sapper-tailwindcss.zip](https://github.com/EricPKerr/sapper-tailwindcss/files/4007439/sapper-tailwindcss.zip)

**Comment by EricPKerr** [comment]
Definitely - please open a PR and I will merge.  Thanks!

**Comment by GitGangGuy** [comment]
@RStrydom Yeah, I saw that tutorial as well. But I was weirded out by the fact that you’d have to import the tailwind.css file for every component you’d want to use it in. I’m not sure if just adding it to the server.js would mitigate that (like it does with this solution). Could anybody assist me with the source code I currently have? That would be amazing!

**Comment by GitGangGuy** [comment]
Alright, so I just force-pushed a possible fix for the problem on my fork - it works great and uses both `svelte-preprocess` AND `rollup-plugin-postcss`. (Svelte-Preprocess for [Less](http://lesscss.org/) support, global styles and overall greatness, and keeping the postcss plugin for easy extraction of the tailwind styles. I'll open a pull request, feel free to modify & merge ;)
